# Generated by Django 5.0.9 on 2025-01-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_test_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='market_cap',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
